### ISSUE TITLE
BUG: cant type capital X in russian keyboard.

### ISSUE THREAD

**Issue by Dani-l4** [Mossop/vscode-backticks#47]
In russian keyboard "x" is the "[" / "{" button. In English keyboard layout its working fine. With russian you cannot type capital "Х" (it became "{" for some reason). Moreover, I removed the hotkeys and, in principle, as expected, the extension stopped working. I deleted the extension, installed it again, but the hotkeys were not added back. I restarted vsc after each step - nothing helps.

**Comment by Mossop** [comment]
This is likely the same issue as #44 and basically a known problem where the only way I found at the time to trigger the extension is by setting it as a keyboard shortcut, but the keyboard shortcut has to be different for different locales. Maybe there is something new since then but I haven;t had time to look at this.

**Comment by Mossop** [comment]
This is a dupe of #44.
