### ISSUE TITLE
Possible solution for #3 #4 #6

### ISSUE THREAD

**Issue by SCLeoX** [Mossop/vscode-backticks#8]
I assume you do not want to parse the entire file just to know how are quotes are paired to each other. So I  tried to create a simple algorithm to do that. I am not sure if it is robust enough. More testing is required.

https://codepen.io/SCLeo/pen/WgbzoZ

**Comment by SCLeoX** [comment]
Well, I just realized that single quotes and double quotes can appear in template strings as well. Since templates do not require a '\' for multiline, I think parsing the entire file is required.

updated pen: https://codepen.io/SCLeo/pen/KxwRyj

**Comment by Mossop** [comment]
I wonder what the performance of that is going to be like on large files and I wonder if there is a way to utilise the fact that VS Code must already be parsing the file for this.

Either way I think before implementing anything more complex than what it currently is I'd really to take a crack at #7 so that there can be some regression testing going forwards.

**Comment by SCLeoX** [comment]
I agree, but I have no experience with vscode extension development at all. Is there anything I can help with writing test cases?

**Comment by Mossop** [comment]
My experience is pretty low too, particularly I've never written tests. I was planning to give it a try when I'm back in the office tomorrow

**Comment by SCLeoX** [comment]
Ok, good luck.
